name: Build (Linux)
on: workflow_dispatch

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.290.0
          cache: false
      - name: Fetch GLFW source
        shell: bash
        run : |
          python .github/workflows/download-file.py https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip ../glfw.zip
          cd ..
          unzip glfw.zip
      - name: Fetch GLFW dependencies
        shell: bash
        run : | 
          sudo apt-get update
          sudo apt-get install xorg-dev
      - name: Build GLFW
        shell: bash
        run : |
          cd ../glfw-3.4
          cmake -S . -B build -D GLFW_BUILD_WAYLAND=0 -D CMAKE_INSTALL_PREFIX=`pwd`/out
          cd build
          make install
      - name: Build Code
        shell: bash
        run: |
          ls
          node Maekfile.js -q
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-linux
          path: bin/*
          retention-days: 5

